"""create auth_codes and app_sessions tables

Revision ID: 0451270d22eb
Revises: ae5881f0b12c
Create Date: 2026-10-04 17:14:41.382442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0451270d22eb'
down_revision = 'ae5881f0b12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('password_fingerprint', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_app_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_app_sessions_token_hash'))
    )
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('auth_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('code_challenge', sa.String(length=43), nullable=False),
    sa.Column('redirect_uri', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_auth_codes_code_hash'))
    )
    with op.batch_alter_table('auth_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_codes_user_id'))

    op.drop_table('auth_codes')
    with op.batch_alter_table('app_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_sessions_user_id'))

    op.drop_table('app_sessions')
    # ### end Alembic commands ###
