"""create plaid_items table

Revision ID: 176bff1b7811
Revises: 0451270d22eb
Create Date: 2026-10-04 18:32:32.850122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176bff1b7811'
down_revision = '0451270d22eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.String(length=64), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('transactions_cursor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plaid_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_items')),
    sa.UniqueConstraint('item_id', name=op.f('uq_plaid_items_item_id'))
    )
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plaid_items_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plaid_items_user_id'))

    op.drop_table('plaid_items')
    # ### end Alembic commands ###
