"""create login_codes table

Revision ID: 4eafc53ce707
Revises: 5d37c731d08c
Create Date: 2026-10-07 22:07:53.453227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eafc53ce707'
down_revision = '5d37c731d08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hmac', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_codes'))
    )
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_codes_user_id'))

    op.drop_table('login_codes')
    # ### end Alembic commands ###
