"""add trial_used_at to subscriptions

Revision ID: 5d37c731d08c
Revises: 176bff1b7811
Create Date: 2026-10-05 11:18:08.445837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d37c731d08c'
down_revision = '176bff1b7811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_used_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('trial_used_at')

    # ### end Alembic commands ###
