"""create site_visits table

Revision ID: 6afbb870915e
Revises: 4eafc53ce707
Create Date: 2026-10-09 19:45:06.338442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afbb870915e'
down_revision = '4eafc53ce707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('visitor', sa.String(length=16), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_visits'))
    )
    with op.batch_alter_table('site_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_visits_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_visits_created_at'))

    op.drop_table('site_visits')
    # ### end Alembic commands ###
