"""add period start and cancellation reason to subscriptions

Revision ID: ae5881f0b12c
Revises: 3baf908ea7df
Create Date: 2026-10-02 05:48:29.414755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5881f0b12c'
down_revision = '3baf908ea7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('current_period_start')

    # ### end Alembic commands ###
