"""create oauth_identities table

Revision ID: f14fb3f708ab
Revises: f750ec1fdb0b
Create Date: 2026-10-01 07:15:47.547806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14fb3f708ab'
down_revision = 'f750ec1fdb0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name=op.f('uq_oauth_identities_provider')),
    sa.UniqueConstraint('user_id', 'provider', name=op.f('uq_oauth_identities_user_id'))
    )
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_identities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_identities_user_id'))

    op.drop_table('oauth_identities')
    # ### end Alembic commands ###
